### ISSUE TITLE
Internal Server Error when loading a file from Zenoo/LightQuery

### ISSUE THREAD

**Issue by Zenoo** [schme16/gitcdn.xyz#49]
It works fine for other repos I'm using it on, but for some reason it won't work on Zenoo/LightQuery.

**Example:** [`https://gitcdn.link/repo/Zenoo/LightQuery/master/light-query.min.js`](https://gitcdn.link/repo/Zenoo/LightQuery/master/light-query.min.js)

Which should link to [`https://raw.githubusercontent.com/Zenoo/LightQuery/master/light-query.min.js`](https://raw.githubusercontent.com/Zenoo/LightQuery/master/light-query.min.js)

**Comment by schme16** [comment]
Still good to note it, I'll look into it and reopen if required!

**Comment by Zenoo** [comment]
Same issue on https://gitcdn.link/repo/Zenoo/FormulaJS/v0.2.6/formula.min.js

If it's anything like before, it should be solved soon, but it's still a little annoying.

**Comment by schme16** [comment]
The file seems to be loading correctly from my ray, can you check if it's
still failing for you (after a browser cache purge)?

This was probably a side effect of the service requiring a top level cache
purge a few days ago (Sorry!)

**Comment by Zenoo** [comment]
It's working now.
I also noticed this behavior when someone load the ressource before it has been created.

Let's say I load https://gitcdn.link/repo/Zenoo/FormulaJS/v0.5.6/formula.min.js before I created the tag v0.5.6, once I create said tag, the file will send a 500 error.

**Comment by Kristinita** [comment]
@schme16 , ping.

+ Raw GitHub URL: **<https://raw.githubusercontent.com/kellyk/visualize/master/visualize.js>**
+ GitCDN URL: **<https://gitcdn.xyz/repo/kellyk/visualize/master/visualize.js>**

I get `Internal Server Error`.

Thanks.

**Comment by Kristinita** [comment]
Already works.

Thanks.

**Comment by FranklinYu** [comment]
Internal server error for:

https://gitcdn.link/repo/schme16/gitcdn.xyz/1112b6595b2bcf9d7e3355891a91d72587623f0d/res/21457_GitCDN_logo_01.png

Seems to affect all PNG images.

**Comment by schme16** [comment]
I wasn't able to reproduce the issue on my side (the link you posted works just fine from here), but in case it was a cloudflare ray issue/bad cache or something, I did a cdn and local purge of the cache, and restarted the server.

Let me know if the issue persists past the next few hours!
